site_name: HealOps Docs
repo_url: https://github.com/larssb/HealOps
theme: readthedocs
pages:
  - Home: 'index.md'
  - HealOps:
    - 'HealOps-Motivation.md'
    - 'HealOps-Deploying.md'
    - 'HealOps-ArchitectureAndInnerWorkings.md'
    - Troubleshooting:
      - 'HealOps-Troubleshooting-OpenTSDB'
  - HealOpsPackages:
    - 'HealOpsPackages-What.md'
    - 'HealOpsPackages-Developing.md'
  - The project:
    - 'Who.md'
    - 'Contributing.md'
    - 'MoreHealOps.md'