markdown_extensions:
  - toc:
      permalink: "#"
repo_url: https://github.com/larssb/HealOps
site_name: HealOps
theme: readthedocs
pages:
  - Home: 'index.md'
  - HealOps:
    - The motivation: 'HealOps-Motivation.md'
    - Deploying HealOps: 'HealOps-Deploying.md'
    - An architectural overview: 'HealOps-ArchitectureAndInnerWorkings.md'
    - Troubleshooting:
      - OpenTSDB: 'HealOps-Troubleshooting-OpenTSDB.md'
      - Package management: 'HealOps-Troubleshooting-PackageManagement.md'
  - HealOpsPackages:
    - What?: 'HealOpsPackages-What.md'
    - Getting started: 'HealOpsPackages-GettingStarted.md'
    - Coding: 'HealOpsPackages-Developing.md'
  - Metrics:
    - Round and about: 'Metrics.md'
    - Visualizing: 'Grafana-VisualizingMetrics.md'
  - Package Management:
      - Getting ready for managing packets: 'PackageManagement-Setup.md'
      - Every day management: 'PackageManagement-TheDailyRoutine.md'
  - The project:
    - Who's behind: 'Who.md'
    - Contributing: 'Contributing.md'
    - More info: 'MoreHealOps.md'